# Generated by Django 6.0.1 on 2026-03-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_project_og_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(help_text='Nombre que se mostrará en la URL', max_length=200, unique=True, verbose_name='Slug'),
        ),
    ]
