# Generated by Django 6.0.1 on 2026-04-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_project_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttechnology',
            name='icon',
        ),
    ]
