# Generated by Django 5.2.12 on 2026-06-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_certificate_alter_skill_id_alter_skillcategory_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='url',
            field=models.URLField(max_length=255, verbose_name='URL del certificado'),
        ),
    ]
